version: '2.0'
services:
  mqtt_broker:
    container_name: mqtt_broker
    image: 
      "eclipse-mosquitto:2.0.15"
    ports:
      - "1883:1883"
    expose:
      - '1883'
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
      - ./mosquitto/log/:/mosquitto/log/
      - ./mosquitto/log/:/mosquitto/data/
    networks:
      iot_network:
        aliases:
          - broker
    restart: always

  node-red:
    image: nodered/node-red:3.1.4-minimal
    container_name: node-red
    ports:
      - "1880:1880"
    restart: always
    volumes:
      - './nodered:/home/work'
    networks:
      iot_network:
        aliases:
          - node_red

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    expose:
      - '8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - influxdb-storage:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    restart: always
    networks:
      iot_network:
        aliases:
          - influx

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    restart: always
    volumes:
      - './grafana:/home/grafana'
    networks:
      iot_network:
        aliases:
          - grafan

volumes:
  influxdb-storage:
    driver: local
  influxdb-config:
    driver: local
  grafana:
    driver: local
  node-red-data:
    driver: local

networks:
  iot_network:

